[package]
name = "previewer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argparse = "0.2.2"
ffmpeg-next = "7.0.0"
image = "0.25.0"
